### ISSUE TITLE
remove-package tool doesn't work off current plugin-seed

### ISSUE THREAD

**Issue by pekevski** [NativeScript/plugin-tools#8]
Looks like the plugin seed only has demos for plain/ts and angular apps in the `/apps` directory. So when a developer `npm run add`'s a plugin it will only get added / removed from the following directories:
```
/apps/demo
/apps/demo-angular
```
Looks like the [remove-package code](https://github.com/NativeScript/plugin-tools/blob/18679891a72bfb3f464eaafd3f31265374d31154/packages/plugin-tools/src/generators/remove-package/index.ts#L24) loops through all flavours of demo without actually checking they exist in the file tree.

Would the appropriate fix be to 
1. Add all the demo flavours to `/app` with a package.json; or 
2. Add something like:
  ```
  for (const t of getDemoTypes()) {
      const demoAppRoot = getDemoAppRoot(t);
      if (tree.exists(demoAppRoot)) {
          removeDemoFiles(tree, t, demoAppRoot);
          removeFromDemoIndex(tree, t, demoAppRoot);
          updateDemoDependencies(tree, demoAppRoot);
      }
  }
  ```
  to `packages/plugin-tools/src/generators/remove-package/index.ts`?

(Happy to make the fix based on the best way forward as well)

**Comment by pekevski** [comment]
Looks like #7 tries to address the issue, however I think checking for existence covers a wider range of possibilities

**Comment by NathanWalker** [comment]
@pekevski thanks for ping on this. I’m going to work on getting updates out by tomorrow afternoon on this.

**Comment by NathanWalker** [comment]
Actually @pekevski i like your suggested fix better if you want to PR that? I may revert the other tomorrow as I think your suggestion would cover more and be simpler.

**Comment by pekevski** [comment]
Sure ill quickly do it now for you
